Collecting GPy
  Using cached GPy-0.8.8.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7 in /sscc/opt/anaconda/lib/python2.7/site-packages (from GPy)
Collecting scipy>=0.16 (from GPy)
  Using cached scipy-0.16.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /sscc/opt/anaconda/lib/python2.7/site-packages (from GPy)
Installing collected packages: scipy, GPy
  Running setup.py install for scipy
    Complete output from command /sscc/opt/anaconda/bin/python -c "import setuptools, tokenize;__file__='/tmp/cbe117/pip-build-mg4_yx/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/cbe117/pip-XiNt5q-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['/sscc/opt/anaconda/lib']
      NOT AVAILABLE
    
    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['/sscc/opt/anaconda/lib']
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /sscc/opt/anaconda/lib
      libraries lapack_atlas not found in /sscc/opt/anaconda/lib
    numpy.distutils.system_info.atlas_3_10_threads_info
      NOT AVAILABLE
    
    atlas_3_10_info:
      libraries satlas,satlas not found in /sscc/opt/anaconda/lib
      libraries lapack_atlas not found in /sscc/opt/anaconda/lib
    numpy.distutils.system_info.atlas_3_10_info
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /sscc/opt/anaconda/lib
      libraries lapack_atlas not found in /sscc/opt/anaconda/lib
    numpy.distutils.system_info.atlas_threads_info
      NOT AVAILABLE
    
    atlas_info:
      libraries f77blas,cblas,atlas not found in /sscc/opt/anaconda/lib
      libraries lapack_atlas not found in /sscc/opt/anaconda/lib
    numpy.distutils.system_info.atlas_info
      NOT AVAILABLE
    
    /sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/system_info.py:1505: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    lapack_info:
      libraries lapack not found in ['/sscc/opt/anaconda/lib']
      NOT AVAILABLE
    
    /sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/system_info.py:1516: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    lapack_src_info:
      NOT AVAILABLE
    
    /sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/system_info.py:1519: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
      NOT AVAILABLE
    
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/cbe117/pip-build-mg4_yx/scipy/setup.py", line 253, in <module>
        setup_package()
      File "/tmp/cbe117/pip-build-mg4_yx/scipy/setup.py", line 250, in setup_package
        setup(**metadata)
      File "/sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/cbe117/pip-build-mg4_yx/scipy/setup.py", line 175, in configuration
        config.add_subpackage('scipy')
      File "/sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/sscc/opt/anaconda/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------
